import Link from "next/link";
import { weapons } from "./algorithm-data";
const english: Record<string, {role:string; principle:string; assumption:string; caution:string; steps:string[]; implementation:string[]}> = {
  "ml-kem": {role:"Key establishment",principle:"ML-KEM encodes a short secret in noisy module-lattice equations. The receiver uses the short secret to recover the encapsulated value. The KEM outputs a ciphertext and a 32-byte shared secret.",assumption:"Module-LWE, with a Fujisaki-Okamoto style conversion and implicit rejection.",caution:"A KEM does not encrypt application messages. Combine shared secrets using a protocol-defined key schedule. The internal K-PKE component is not a standalone application encryption scheme.",steps:["Expand the matrix from a seed, sample short secret and error vectors, and produce the encapsulation and decapsulation keys.","Generate fresh randomness, derive the encryption coins, and output a ciphertext and a shared secret.","Recover a candidate message using the decapsulation key.","Re-encrypt the recovered candidate and compare ciphertexts without leaking key-dependent branches.","Return a pseudorandom rejection secret for invalid ciphertexts without exposing a decryption oracle."],implementation:["Check public-key and ciphertext lengths.","Audit constant-time comparisons, NTT and compression paths.","Use the protocol's specified hybrid combiner and key schedule."]},
  "ml-dsa": {role:"Digital signatures",principle:"ML-DSA uses noisy module-lattice public keys and short responses bound to a message-dependent challenge. Rejection sampling controls the response distribution.",assumption:"Module-LWE and Module-SIS, with hash-based challenge generation.",caution:"Rejection sampling is security-critical. A signature authenticates a message; it does not hide it. Distinguish ML-DSA from older Dilithium encodings.",steps:["Expand the matrix and sample short secret vectors.","Sample a masking vector and compute the high bits of its matrix product.","Bind the message representative and commitment to a sparse challenge.","Compute the response; reject samples that fail the specified bounds.","Use the public key and hint to reconstruct the commitment and check the challenge."],implementation:["Use FIPS 204 encodings and domain separation.","Test long rejection paths and fault handling.","Preserve the context string and pure versus prehash mode."]},
  "slh-dsa": {role:"Stateless hash-based signatures",principle:"SLH-DSA combines FORS, WOTS+ and a hypertree. Its stateless design avoids a persistent one-time-key counter, while signatures remain substantially larger than lattice signatures.",assumption:"Hash-function security, including the required domain separation and address structure.",caution:"The full 12-parameter FIPS 205 set combines SHA2 or SHAKE with 128, 192 or 256-bit parameter families and s or f variants. Select by bandwidth and signing cost.",steps:["Derive secret and public seeds and construct the top-tree root.","Derive message randomness and hash the message into indices and a FORS digest.","Sign the digest with FORS and recover its public key.","Authenticate that key with WOTS+ and Merkle paths through the hypertree.","Reconstruct all roots and compare the final root with the public key."],implementation:["Check hash family and the complete parameter name.","Validate address construction and domain separation.","Account for signature size before protocol deployment."]},
  "fn-dsa": {role:"Compact lattice signatures",principle:"FN-DSA is derived from Falcon. It uses short NTRU lattice bases and Gaussian sampling to produce compact signatures.",assumption:"Short-vector problems in NTRU lattices; security also depends on correct Gaussian sampling.",caution:"Checked on 8 October 2026: NIST lists Falcon as undergoing standardization. This site provides an explanatory reference, not a finalized FN-DSA implementation. Falcon estimates must not be treated as final FIPS 206 parameters.",steps:["Generate an NTRU basis and a public polynomial relation.","Hash the nonce and message to a lattice target.","Sample a short lattice response using the private basis.","Encode the response and include the required nonce.","Check the public relation, encoding constraints and norm bound."],implementation:["Audit Gaussian sampling and precision requirements.","Review timing, fault and floating-point behavior.","Follow final standard encodings when available."]},
};
export default function AlgorithmArticle({algorithm,en=false}:{algorithm:string;en?:boolean}) {
  const item=weapons.find(item=>item.id===algorithm)!;
  const translated=english[algorithm];
  const base=en?"/en/pqc/":"/pqc/";
  const sections=en?[["principle","Principle"],["flow","Algorithm flow"],["parameters","Parameters"],["engineering","Implementation"],["sources","Sources"]]:[["principle","数学原理"],["flow","运算流程"],["parameters","参数与体积"],["engineering","实现关注"],["sources","原始资料"]];
  const source=algorithm==="fn-dsa"?"https://csrc.nist.gov/projects/post-quantum-cryptography":`https://csrc.nist.gov/pubs/fips/${algorithm==="ml-kem"?203:algorithm==="ml-dsa"?204:205}/final`;
  return <main id="main-content" className="content-page algorithm-page" lang={en?"en":"zh-CN"}><header><Link href={en?"/en/pqc":"/pqc-arsenal"}>{en?"Algorithm Guide":"密码图鉴"}</Link><p>{en?translated.role:item.role} · {item.code}</p><h1>{item.name}</h1><p>{en?(algorithm==="fn-dsa"?"Standardization underway · checked 2026-10-08":"Final standard · 2024"):item.status}</p></header><div className="algorithm-reading-layout"><nav className="algorithm-toc" aria-label={en?"On this page":"本页目录"}>{sections.map(([id,title])=><a href={"#"+id} key={id}>{title}</a>)}<hr/>{weapons.map(other=><Link href={base+other.id} aria-current={other.id===algorithm?"page":undefined} key={other.id}>{other.name}</Link>)}</nav><div>
    <section id="principle"><h2>{sections[0][1]}</h2><p>{en?translated.principle:item.principle}</p><p>{en?translated.assumption:item.assumption}</p>{item.equations.map(equation=><p className="algorithm-formula" key={equation}>{equation}</p>)}</section>
    <section id="flow"><h2>{sections[1][1]}</h2><ol className="algorithm-steps">{item.flow.map((step,i)=><li key={step.title}><h3>{step.title}</h3><code>{step.formula}</code><p>{en?translated.steps[i] || translated.steps[translated.steps.length-1]:step.detail}</p></li>)}</ol></section>
    <section id="parameters"><h2>{sections[2][1]}</h2><p>{en?"Sizes below describe algorithm material, excluding protocol headers, certificates and transport framing.":"以下为算法材料体积，不含协议头、证书与传输开销。"}</p><div className="algorithm-table-wrap"><table><thead><tr><th>{en?"Parameter set":"参数集"}</th><th>{en?"Security category":"安全类别"}</th><th>{en?"Public key":"公钥"}</th><th>{algorithm==="ml-kem"?(en?"Ciphertext":"密文"):(en?"Signature":"签名")}</th></tr></thead><tbody>{item.levels.map(level=><tr key={level.name}><td>{level.name}</td><td>{en?level.security.replace(/NIST (\d) 级/,"NIST category $1").replace("约 ","Approx. "):level.security}</td><td>{level.publicKey}</td><td>{level.payload}</td></tr>)}</tbody></table></div><p>{en?translated.caution:item.caution}</p>{algorithm==="fn-dsa"&&<p>{en?translated.caution:"核对日期：2026-10-08。NIST 项目页仍标示 Falcon 标准化工作正在进行；表中为 Falcon 原理参考体积，并非 FIPS 206 最终参数。"}</p>}</section>
    <section id="engineering"><h2>{sections[3][1]}</h2><ul>{(en?translated.implementation:item.implementation).map(line=><li key={line}>{line}</li>)}</ul>{algorithm!=="fn-dsa"&&<a className="silver-button" href={(en?"/pqc-practice/index-en.html":"/pqc-practice/index.html")+"?tab="+(algorithm==="ml-kem"?"kem":"signature")+"&algorithm="+algorithm}>{en?"Run an example":"运行一个示例"}</a>}</section>
    <section id="sources"><h2>{sections[4][1]}</h2><a href={source} target="_blank" rel="noreferrer">{algorithm==="fn-dsa"?"NIST PQC standardization status":item.code}</a><p>{en?"This is a teaching guide. Consult the original standard for encoding, domain separation, validation and implementation requirements.":"本页为教学说明，编码、域分离、输入检查和实现要求以原始标准为准。"}</p></section>
  </div></div></main>;
}
